version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: loja_online_db
    restart: always
    environment:
      - MYSQL_DATABASE=loja_online
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  app_loja_online:
    build: .
    container_name: app_loja_online
    restart: "no"
    ports:
        - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/loja_online
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
        - my-network

volumes:
  mysql-volume:
    driver: local

networks:
  my-network:
    driver: bridge